<script>
jQuery.noConflict(); 
/* calling thumbnailScroller function with options as parameters */
(function($){
var isTouch = 'ontouchstart' in window && !(/hp-tablet/gi).test(navigator.appVersion);

if(isTouch){
  $scrollerType = "clickButtons";
}else{
  $scrollerType = "hoverPrecise";
}

$(document).ready(function() {
  $(".feature-scroller").thumbnailScroller({ 
        scrollerType:$scrollerType, 
        scrollerOrientation:"horizontal", 
        scrollSpeed:2, 
        scrollEasing:"easeOutCirc", 
        scrollEasingAmount:200, 
        acceleration:4, 
        scrollSpeed:500, 
        noScrollCenterSpace:10, 
        autoScrolling:0, 
        autoScrollingSpeed:2000, 
        autoScrollingEasing:"easeInOutQuad", 
        autoScrollingDelay:500 
    });


   $(".jm-boxwrap").bind("click",function(){
       
         window.location = $(this).find("div.jmzin-section a").attr("href");
   }); 
}); 

})(jQuery);

</script>

<?php
$cols = $config['perrow'];
$count = 0;

if($total < $cols) $cols = $total;
if (!$cols) return;
$width = 100/$cols;

?>
<div class="jm-product-list-bycat">
    <div class="clearfix category-listing">
        <div class="main">  
            <div class="inner clearfix">
                <?php if($config['title']){?><h2><?php echo $config['title']; ?></h2><?php }; ?>
            </div>
        </div>
        <div class="feature-scroller jThumbnailScroller">
             <div class="jTscrollerContainer">
                 <div class="jTscroller">
                    <?php
                        $j = 0;
                        for ($z = 0; $z < $cols; $z ++) :
                            $cls = $cols==1?'full':($z==0?'left':($z==$cols-1?'right':'center')); ?>
                            <div class="jm-cat-<?php echo $cls;?> feature-scroller-slide" >
                                
                                <?php for ($y = 0; $y < ($total / $cols) && $j<$total; $y ++) :
                                  $row = $listall[$j];                    
                                  include(dirname(__FILE__).DIRECTORY_SEPARATOR.'item.phtml');
                                  $j++;
                                endfor; ?>
                                
                            </div>              
                        <?php endfor; ?>
                 </div>     
              </div>
              <a href="#" class="jTscrollerPrevButton"></a>
              <a href="#" class="jTscrollerNextButton"></a>              
        </div>
    </div>
</div>

