
<div class="cartmessage">
  <div class="message"><?php echo $cartreturn['status'].":".$cartreturn['message']; ?></div> 
   <div class="button">
     <button class="button btn-continue jmcontinue" title="Continue Shopping" type="button"><span><span>Continue Shopping</span></span>    </button>
     <button class="button btn-continue jmgocart" title="Go Cart" type="button"><span><span>Go to Cart</span></span></button>
   </div>
</div>
