<?php if(Mage::helper('jmquickview')->get('show')) { ?>

<script type="text/javascript">
  var baseurl = "<?php echo Mage::getBaseUrl(); ?>"
</script>

<?php if(!defined('JM_ADD_JQUERY')): ?>
	<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery/jquery.js') ?>"></script>
	<?php define('JM_ADD_JQUERY', true); ?>
<?php endif; ?>
<?php if(!defined('JM_ADD_COLORBOX')): ?>
	<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery/plugins/colorbox/jquery.colorbox.js') ?>"></script>
	<?php define('JM_ADD_COLORBOX', true); ?>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmquickview/js/jmquickview.js') ?>"></script>
<script type="text/javascript">
     jQuery(document).ready(function() {

     	   //move the topcart to the right side
		     if(!jQuery("#ja-mycartleft").length) {
			     jQuery('<div id="ja-mycartleft" />').appendTo(jQuery("#ja-wrapper"));
			     jQuery("#ja-mycartleft").html(jQuery("#ja-mycart").html());
			     jQuery("#ja-mycartleft #jmajaxcartscroll").attr("id","jmajaxcartscrollleft");
		         mycartobj = jQuery("#ja-mycart").data("mycartobj");
		         mycartobj.bindcartEvents();
		        
			     //update the right cart after topcart is updated
			     jQuery("#ja-mycart").bind("afterupdatecart",function(){
			         jQuery("#ja-mycartleft").html(jQuery("#ja-mycart").html());
					 jQuery("#ja-mycartleft #jmajaxcartscroll").attr("id","jmajaxcartscrollleft");
					 jQuery(".jmoverlay").remove();
			     });

		    }else{
		   	 jQuery("#ja-mycartleft").show();
		    } 
           // Handler for .ready() called.
     });
     
</script> 
<?php } ?>